export const ADD_PRODUCT_TO_CART  ="ADD_PRODUCT_TO_CART"
export const ADD_PRODUCT_TO_CART_SUCCESS  ="ADD_PRODUCT_TO_CART_SUCCESS"
export const ADD_PRODUCT_TO_CART_FAIL ="ADD_PRODUCT_TO_CART_FAIL"
export const ADD_PRODUCT_ITEM ="ADD_PRODUCT_ITEM"